---
# optimizer options
batch_size: 64
optimizer: 'adam'
learning_rate: 0.01
momentum: 0.9
l2_reg: 0.0001

# lr scheduler options
lr_milestones:
  - 80
  - 100
lr_gamma: 0.1

# training options
epochs: 100

# run options
gpu: 0
no_gpu: false
model: "DeepCNN"
dataset_root: "data/normalized/"
num_workers: 4
no_memory_pinning: false
channels_first: true
as_greyscale: false

# experimental options
subsampling: false
subsample_size: 100


# misc options
log_root: "logs/"
run_name: "template"


