---
# optimizer options
batch_size: 128
optimizer: 'SGD'
learning_rate: 0.1
momentum: 0.9
l2_reg: 0.00001

# lr scheduler options
lr_milestones:
  - 80
  - 100
lr_gamma: 0.1

# training options
epochs: 120

# run options
gpu: 0
no_gpu: false
model: "LSTM"
dataset_root: "data/normalized/"
num_workers: 4
no_memory_pinning: false
channels_first: false
as_greyscale: false

# experimental options
subsampling: false
subsample_size: 100

# dataset one-shot preprocessing options
# size of window to average sequences over
temp_ds_wnd: 10

# dataset options
seq_len: 20
stride: 2
sequential_targets: true


# misc options
log_root: "logs/"
run_name: "template"


