---
# optimizer options
batch_size: 64
optimizer: 'adam'
learning_rate: 0.01
momentum: 0.9
l2_reg: 0.0001

# lr scheduler options
lr_milestones:
  - 20
lr_gamma: 0.1

# training options
epochs: 30

# run options
gpu: 0
no_gpu: false
model: "ShallowCNN_GRU"
dataset_root: "data/normalized/"
num_workers: 4
no_memory_pinning: false
channels_first: true
as_greyscale: false

# augmentation options
trim: true
maxpool: true
averaging: true
average_size: 2
noise: false
subsampling: true
subsample_size: 2
reshape: true
separate_noise: false

# misc options
log_root: "logs/"
run_name: "template"


